environment:
  matrix:
    - stage: Build
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
    - stage: Test
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - stage: Test
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
    - stage: Test
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - stage: Deploy
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019 Preview
platform: Any CPU
skip_branch_with_pr: true
configuration: Release

matrix:
  fast_finish: true
for:
  -
    matrix:
      only:
        - stage: Build
    install:
      - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
    before_build:
      - ps: Vsix-IncrementVsixVersion | Vsix-UpdateBuildVersion
      - ps: Vsix-TokenReplacement Conan.VisualStudio\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'
      - nuget restore
    build_script:
      - msbuild /p:DeployExtension=false /p:verbosity=detailed
    artifacts:
      - path: Conan.VisualStudio\bin\Release\Conan.VisualStudio.vsix
        name: Conan Visual Studio Extension
  -
    matrix:
      only:
        - stage: Test
    init:
      - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    build_script:
      - ps: .\vsix\download_artifact.ps1
    test_script:
      - ps: write-host "Test scenario"
      - ps: .\vsix\install_vsix.ps1
      - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" && devenv /ConanVisualStudioVersion /?
      - ps: .\vsix\check_installed.ps1
      - ps: write-host "Done"
  -
    matrix:
      only:
        - stage: Deploy
    skip_non_tags: true
    build_script:
      - ps: .\vsix\download_artifact.ps1
    test_script:
      - ps: write-host "Deploy scenario"
