image:
  - Visual Studio 2019 Preview
  - Visual Studio 2017
platform: Any CPU
skip_branch_with_pr: true
configuration: Release

matrix:
  - fast_finish: true
for:
  -
    matrix:
      only:
        - image: Visual Studio 2019 Preview
    test_script:
      - ps: write-host "Visual Studio 2019 Preview"

  -
    matrix:
      only:
        - image: Visual Studio 2017
    test_script:
      - ps: write-host "Visual Studio 2017"

