environment:
  matrix:
    - stage: Build
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - stage: Test
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - stage: Test
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    #- stage: Test
    #  APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    - stage: Deploy
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
platform: Any CPU
skip_branch_with_pr: false
configuration: Release

matrix:
  fast_finish: true
for:
  -
    matrix:
      only:
        - stage: Build
    install:
      - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
    before_build:
      - ps: Vsix-IncrementVsixVersion -versionType revision | Vsix-UpdateBuildVersion
      - ps: Vsix-TokenReplacement Conan.VisualStudio\source.extension.cs 'Version = "([0-9\\.]+)"' 'Version = "{version}"'
      - nuget restore
    build_script:
      - msbuild /p:DeployExtension=false /p:verbosity=detailed
    artifacts:
      - path: Conan.VisualStudio\bin\Release\Conan.VisualStudio.vsix
        name: Conan Visual Studio Extension
  -
    matrix:
      only:
        - stage: Test
    build_script:
      - ps: .\vsix\download_artifact.ps1
      - ps: .\vsix\install_vsix.ps1
    test_script:
      - ps: .\vsix\check_installed.ps1
      - ps: write-host "Checked for ${env:APPVEYOR_BUILD_WORKER_IMAGE}"
  -
    matrix:
      only:
        - stage: Deploy
    skip_non_tags: true
    build_script:
      - ps: .\vsix\download_artifact.ps1
    test_script:
      - ps: write-host "Deploy scenario"
    deploy_script:
      - ps: IF ($env:APPVEYOR_REPO_BRANCH -eq "master") {.\vsix\publish.ps1}
      - ps: IF ($env:APPVEYOR_REPO_BRANCH -eq "master") {Vsix- -path ${env:localArtifactPath}}

